version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli@8.3.21
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Building Angular project...
      - ng build --configuration production  

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading to S3...
      - aws s3 sync dist/OMP s3://omp-angular-bucket --delete
      - echo Invalidate CloudFront cache (if using CloudFront)...

artifacts:
  files:
    - '**/*'
  base-directory: dist/OMP
